### get api
GET  http://localhost:8000/api/classify/getClassify
?pageSize=10
&currentPage=1

### hotClassify
GET  http://localhost:8000/api/classify/hotClassify


### update and add api
POST  http://localhost:8000/api/classify/updateClassify
Content-Type: application/json;charset=utf-8

{
  "id":"1",
  "name":"心情随笔-11111"
}